#pragma once

struct [[META]] TestClass
{
    [[META, RANGE(1, 10.5), STEP(0.5), INFO("this is a info")]]
    int a;
};

template<typename T>
struct [[META]] Data
{
    [[META]] T x;
    [[META]] T y;
};

// auto generated by PupilReflTool
#include "generated/test.gen.inl"
