#pragma once

#include "test.h"

namespace TestNsp
{
    template<typename T>
    struct [[META]] TestClass2 : public TestClass
    {
        [[META, RANGE(0, 5), STEP(0.1)]]
        int b;

        [[META]] Data<T> *data;
    };
}
// auto generated by PupilReflTool
#include "generated/test2.gen.inl"
